# Generated by Django 2.2.10 on 2020-12-30 15:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_auto_20201230_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 30, 12, 56, 46, 201355, tzinfo=utc), verbose_name='Начало опроса'),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('answers', models.ManyToManyField(blank=True, related_name='vote_answer', to='vote.Answer', verbose_name='Ответы')),
                ('votes', models.ManyToManyField(blank=True, related_name='user_votes', to='vote.Vote', verbose_name='Опросы')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'custom_user',
            },
        ),
    ]
