# Generated by Django 2.2.10 on 2020-12-30 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_auto_20201230_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 30, 12, 58, 16, 257633, tzinfo=utc), verbose_name='Начало опроса'),
        ),
    ]
