# Generated by Django 2.2.10 on 2020-12-30 16:02

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0009_auto_20201230_1558"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="id"
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 12, 30, 13, 2, 50, 985652, tzinfo=utc),
                verbose_name="Начало опроса",
            ),
        ),
    ]
